---
title: "Yuqing's mtcars application on flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    #orientation: rows
    vertical_layout: scroll
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
```

[comment]: <> (https://www.kaggle.com/philippsp/interactive-dashboards-in-r/report)
[comment]: <> (https://www.quackit.com/css/css_color_codes.cfm)


```{r}
View(mtcars)
```



Layout 1 {data-orientation=rows data-icon="fa-bar-chart"}
=====================================


Row
-----------------------------------------------------------------------


### _Total number of cars_

```{r}
No.cars <- mtcars %>% count
valueBox(No.cars, icon = "glyphicon-phone")
```

### _The Fastest: Ford Pantora L_

```{r}
aaa <- "s";
smallest.qsec <- mtcars %>%
  select(qsec) %>% min
valueBox(paste(smallest.qsec, aaa), icon = "glyphicon-fire", color = "#800000")
```


### _The Most Powerful: Maserati Bora_

```{r}
bbb <- "hp";
largest.hp <- mtcars %>%
  select(hp) %>% max
valueBox(paste(largest.hp, bbb), icon = "glyphicon-tower", color = "#FFD700")
```

### _The Economist: Toyota Corolla_

```{r}
ccc <- "mpg"
largest.mpg <- mtcars %>%
  select(mpg) %>% max
valueBox(paste(largest.mpg, ccc), icon = "glyphicon-pushpin", color = "#228B22")
```


Column {data-width=250}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=750}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```


Layout 2 {data-icon="fa-area-chart"}
=====================================  

Column {data-width=450}
-------------------------------------


### Rating

```{r}
rate <- 85
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


Column {data-width=450}
-------------------------------------


### Score

```{r}
score <- 3
gauge(score, min = 0, max = 10, gaugeSectors(
  success = c(8, 10), warning = c(4, 7), danger = c(0, 3)
))
```
